PolyversCmd:
  projects:
    - pname: co2mpas
      basepath: .

    - pname: co2sim
      basepath: pCO2SIM

    - pname: co2gui
      basepath: pCO2GUI

    - pname: co2dice
      basepath: pCO2DICE

    - pname: webstamper
      basepath: pWebStamper
Project:
  pvtag_format: '{pname}-{vprefix}{version}'
  pvtag_regex: |-
    (?xmi)
        ^(?P<pname>{pname})
        -
        {vprefix}(?P<version>\d[^-]*)
        (?:-(?P<descid>\d+-g[a-f\d]+))?$
