PolyversCmd:
  projects:
  - pname: co2mpas
    basepath: .
  - pname: webstamp
    basepath: co2mpas/sampling/webstamp
Project:
  pvtag_format: '{pname}-{vprefix}{version}'
  pvtag_regex: |-
    (?xmi)
        ^(?P<pname>{pname})
        -
        {vprefix}(?P<version>\d[^-]*)
        (?:-(?P<descid>\d+-g[a-f\d]+))?$
