## monorepo utilities for the developers
#
BUILDCMDS		:= wheel develop uninstall clean

default:
	@echo Specify one of: $(BUILDCMDS)


wheel:
	python setup.py bdist_wheel

## Install all projects in "develop" mode.
develop:
	pip install -e .

uninstall:
	pip uninstall -y $(PNAME)

clean:
	rm -rf build/* dist/* doc/_build


.PHONY: default $(BUILDCMDS)
