version: '3'
services:
  co2mpas-debian:
    container_name: co2mpas
    image: ${CO2MPAS_TAG_DEBIAN-vinci1it2000/co2mpas-debian:latest}
    build:
      context: ..
      dockerfile: ./docker/debian/Dockerfile
    command: ${CO2MPAS_CMD-co2mpas run ./input -O ./output}
