version: '3'
services:
  co2mpas:
    container_name: co2mpas
    image: ${CO2MPAS_TAG-vinci1it2000/co2mpas:latest}
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    environment:
      - co2mpas_VERSION=${co2mpas_VERSION-0.0.0}
    command: ${CO2MPAS_CMD-co2mpas batch ./input -O ./output}